In [1]:
phi = 0.2;
L = 10000; %ft
A = 200000; %ft^2
mu = 1; %cp
Bw = 1; %rb/stb
ct = 1e-6; %1/psi

deltaX = [2000 3000 1500 3500]; %ft
ki = [10 100 50 20]; %ft

Pinitial = 1000; %psi
Pb = 2000; %psi

In [2]:
kinterblock = (deltaX(1:end-1) + deltaX(2:end)) ./ ...
              ((deltaX(1:end-1) ./ ki(1:end-1)) + (deltaX(2:end) ./ ki(2:end)))

kinterblock =

   21.7391   75.0000   24.3902


In [3]:
Tinterblock = 2 * kinterblock * A ./ (mu * Bw * (deltaX(1:end-1) + deltaX(2:end)))

Tinterblock =

   1.0e+03 *

    1.7391    6.6667    1.9512


In [4]:
T1 = ki(1) * A / (mu * Bw * deltaX(1))

T1 =

        1000


In [5]:
T = (diag([Tinterblock(1) + 2 * T1, Tinterblock(1:end-1) + Tinterblock(2:end), Tinterblock(end)]) + ...
    diag(-Tinterblock, 1) + diag(-Tinterblock, -1)) * 6.33e-3

T =

   23.6687  -11.0087         0         0
  -11.0087   53.2087  -42.2000         0
         0  -42.2000   54.5512  -12.3512
         0         0  -12.3512   12.3512


In [6]:
B = diag(A * deltaX * phi * ct / Bw)

B =

    80     0     0     0
     0   120     0     0
     0     0    60     0
     0     0     0   140


In [7]:
P0 = ones(4,1) * Pinitial

P0 =

        1000
        1000
        1000
        1000


In [8]:
Q = zeros(4,1);
Q(1) = 2 * Pb * T1 * 6.33e-3

Q =

       25320
           0
           0
           0


In [9]:
deltaT=1; %day
Pn = P0;

for i=1:3

   A = T + B / deltaT;
   b = (B / deltaT) * Pn + Q;
   
   Pnp1 = A \ b
   
   Pn = Pnp1;
   
end

Pnp1 =

   1.0e+03 *

    1.1230
    1.0086
    1.0032
    1.0003


Pnp1 =

   1.0e+03 *

    1.2194
    1.0223
    1.0100
    1.0011


Pnp1 =

   1.0e+03 *

    1.2956
    1.0391
    1.0199
    1.0026


In [10]:
deltaT=1; %day
Pn = P0;

for i=1:700

   A = T + B / deltaT;
   b = (B / deltaT) * Pn + Q;
   
   Pnp1 = A \ b;
   
   Pn = Pnp1;
   
end
Pnp1

Pnp1 =

   1.0e+03 *

    2.0000
    2.0000
    2.0000
    2.0000
